/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.android.playground.nova.usage

import dev.android.playground.nova.appcompat.theme
import dev.android.playground.nova.core.base.color

fun extending() {

    theme(name = "MyMainTheme", parent = "Theme.AppCompat.Light") {
        // Simple string attribute
        statusBarColor = color.status_bar_overlay

        // Inline widget style
        actionModeStyle {
            background = color.action_mode_background
        }

        toolbarStyle = null

    }

    // This theme extends another app theme overriding one top-level attribute and another
    // attribute in one of the inline widget styles. The output will create a separate
    // <style> entry with autogenerated name and parent name that points to the autogenerated
    // name for the parent's actionModeStyle
    theme(name = "MyMainTheme.Red", parent = "MyMainTheme") {
        // Conditional string attribute that overrides the value in the parent
        statusBarColor {
            baseline use color.status_bar_overlay_red
            smallestWidth(600) use color.status_bar_overlay_red_wide
        }

        // Inline widget style that overrides the value in the parent
        actionModeStyle {
            background = color.action_mode_background_red
        }
    }

}
