/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.android.playground.nova.usage

import dev.android.playground.nova.appcompat.manual.appCompatThemeManual
import dev.android.playground.nova.core.base.color
import dev.android.playground.nova.core.base.postInit
import dev.android.playground.nova.core.framework.generated.android
import dev.android.playground.nova.core.framework.generated.background_light
import dev.android.playground.nova.core.framework.generated.colorAccent

fun simpleAppCompat() {

    appCompatThemeManual(name = "MyMainTheme", parent = "Theme.AppCompat.Light") {
        // Simple boolean attributes. The first two will be from the android:
        // namespace, while the third will be in the app: (implicit) namespace.
        windowDrawsSystemBarBackgrounds = true
        windowLightStatusBar = true
        windowActionModeOverlay = true

        focusable = true

        // Attributes that point to color resources. The first will be from the android:
        // namespace, while the second will be in the app: (implicit) namespace.
        statusBarColor = android.attr.colorAccent
        actionMenuTextColor = android.color.background_light

        // Inline widget style. The output will create a separate <style> entry with an
        // autogenerated name and correct parent name based on what is defined in the base
        // theme for this widget style
        actionModeStyle {
            background = color.action_mode_background
        }
    }
}

fun main() {
    simpleAppCompat()
    for (entry in postInit()) {
        println("*** " + entry.key + " ***")
        println(entry.value)
        println()
    }

}

