/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.android.playground.nova.usage

import dev.android.playground.nova.appcompat.theme
import dev.android.playground.nova.core.base.bool
import dev.android.playground.nova.core.base.color
import dev.android.playground.nova.core.base.postInit
import dev.android.playground.nova.core.framework.styleables.CoreViewStyleable
import dev.android.playground.nova.core.framework.themes.initializeCoreDictionary

fun simple() {

    theme(name = "MyMainTheme", parent = "Theme.AppCompat.Light") {
        // Simple boolean attributes
        windowDrawsSystemBarBackgrounds = true
        windowActionModeOverlay = true

        windowLightStatusBar = true
        windowLightStatusBar = bool.light
        //windowLightStatusBar = FocusableEnum.auto

        focusable = true
        focusable = bool.focusable
        focusable = CoreViewStyleable.FocusableEnum.auto
        //focusable = 3

        // Attributes that point to color resources
        statusBarColor = color.status_bar_overlay
        actionMenuTextColor = color.action_menu_text_color

        // Inline widget style. The output will create a separate <style> entry with an
        // autogenerated name and correct parent name based on what is defined in the base
        // theme for this widget style
        actionModeStyle {
            background = color.action_mode_background
        }
    }
}

fun main(args: Array<String>) {
    initializeCoreDictionary()
    simple()
    for (entry in postInit()) {
        System.out.println("*** " + entry.key + " ***")
        System.out.println(entry.value)
        System.out.println()
    }

}

